apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  containers:
    - name: mongodb
      image: mongo:3.6.19-xenial
      ports:
        - containerPort: 27017
          name: mongodb-port
